[nas]
192.168.1.56 ansible_user=root ansible_ssh_private_key_file=~/.ssh/id_ed25519 ansible_ssh_common_args='-o StrictHostKeyChecking=no -o ProxyJump=williamewanchuk@23.17.81.63:2222 -o IdentityFile=/home/runner/.ssh/id_ed25519'
